In [1]:
import numpy as np

# Numpy Array

In [2]:
x = np.array([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
type(x)

numpy.ndarray

In [5]:
y = np.array(["a","b","c","d"])

In [6]:
y

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [9]:
#Bütün integerlar string olarak ifade edilecek
z = np.array([1,2,3,"a"])

In [10]:
z

array(['1', '2', '3', 'a'], dtype='<U21')

In [11]:
a = np.array([1,2,3,5,"6"])

In [12]:
a

array(['1', '2', '3', '5', '6'], dtype='<U21')

In [13]:
#bütün veri float olacak
b = np.array([1,2,3,4.5])


In [14]:
b

array([1. , 2. , 3. , 4.5])

In [15]:
#Bütün integer ve floatlar stringe dönüştürlecek
c = np.array([1,2,3,4.5,"6"])

In [16]:
c

array(['1', '2', '3', '4.5', '6'], dtype='<U32')

# Array Tipini Manuel Belirlemek

In [17]:
x = np.array([1,2,3,4.6])

In [18]:
x

array([1. , 2. , 3. , 4.6])

In [21]:
#floatları int olarak cast ettim
x = np.array([1,2,3,4.6], dtype = "int32")

In [22]:
x

array([1, 2, 3, 4], dtype=int32)

In [23]:
x  = np.array([1,2,3,4.6], dtype = "str")

In [24]:
x

array(['1', '2', '3', '4.6'], dtype='<U3')

In [25]:
#Her zaman kesin dönüşüm yapamaz mesela burada a harfini integera çeviremez
x = np.array(["a"], dtype = "int32")

ValueError: invalid literal for int() with base 10: 'a'

In [26]:
x = np.array(["3"], dtype = "int32") #Burada string haldeki 3ü başarı ile integera çevirdi

In [27]:
x

array([3], dtype=int32)

In [4]:
x = np.array(["4.2"], dtype = "int32")

ValueError: invalid literal for int() with base 10: '4.2'

# Elemanları 0 dan oluşan bir array oluşturmak

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros(10, dtype = "str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [35]:
# 3 row(satır) ve 4 column(sütun)'u olan bir array oluşturma
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [54]:
np.zeros((1,2,3,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [49]:
#boolean 0 ı FALSE olarak aldığı için
np.zeros((2,3), dtype = "bool")

array([[False, False, False],
       [False, False, False]])

In [3]:
x = np.zeros((3,8,8,5)) # 3 küme içinde 8 tane 8e 5lik array

In [4]:
x

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],



# Belirli bir elemandan spesifik bir array oluşturma

In [56]:
np.full((4,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [57]:
np.full(4,5,5)

TypeError: Cannot interpret '5' as a data type

In [58]:
np.full(4,5)

array([5, 5, 5, 5])

In [60]:
np.full((4,5), 5.3)

array([[5.3, 5.3, 5.3, 5.3, 5.3],
       [5.3, 5.3, 5.3, 5.3, 5.3],
       [5.3, 5.3, 5.3, 5.3, 5.3],
       [5.3, 5.3, 5.3, 5.3, 5.3]])

In [61]:
np.full((4,5), 5.2, dtype = "str")

array([['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5'],
       ['5', '5', '5', '5', '5']], dtype='<U1')

In [62]:
np.full((4,5),"5.2")

array([['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2'],
       ['5.2', '5.2', '5.2', '5.2', '5.2']], dtype='<U3')

In [63]:
np.full((4,5), 5.3, dtype = "float")

array([[5.3, 5.3, 5.3, 5.3, 5.3],
       [5.3, 5.3, 5.3, 5.3, 5.3],
       [5.3, 5.3, 5.3, 5.3, 5.3],
       [5.3, 5.3, 5.3, 5.3, 5.3]])

# Ardışık Sayılardan Array Oluşturma

In [66]:
np.arange(0,12) # Tek r ile

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [69]:
np.arange(2,12) # ilk belirtileni dahil ediyor sonuncuyu etmiyor

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [71]:
np.arange(2,12,-2)

array([], dtype=int64)

In [72]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

# Bir aralığı eşit uzaklıkta noktalara bölmek

In [64]:
#Default olarak 50 tane döndürür, Hem ilk hem son veriyi dahil ediyor. 1 ve 2 dahil
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [75]:
#Kaç parçaya böleceğini bulmak
np.linspace(1,2, num = 3)

array([1. , 1.5, 2. ])

In [76]:
np.linspace(1,2,num=3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

In [77]:
np.linspace(1,2,30)

array([1.        , 1.03448276, 1.06896552, 1.10344828, 1.13793103,
       1.17241379, 1.20689655, 1.24137931, 1.27586207, 1.31034483,
       1.34482759, 1.37931034, 1.4137931 , 1.44827586, 1.48275862,
       1.51724138, 1.55172414, 1.5862069 , 1.62068966, 1.65517241,
       1.68965517, 1.72413793, 1.75862069, 1.79310345, 1.82758621,
       1.86206897, 1.89655172, 1.93103448, 1.96551724, 2.        ])

In [79]:
# Floatlarda da geçerli
np.linspace(1.5, 4.7, 3)

array([1.5, 3.1, 4.7])

# Normal Distribution'dan Çekilmiş Değerler İle Array Oluşturmak

In [80]:
np.random.normal(0, 1, (3,4)) # ortalaması sıfır, standart sapması 1, 3e 4lük bir array

array([[ 1.22391232,  0.10360259,  0.40699279,  1.40798937],
       [ 1.31746539,  0.50169145, -0.19201363,  1.08489913],
       [ 0.21674149,  0.56300738, -1.26625844,  1.24175243]])

In [83]:
np.random.normal(0,100,(4,5)) # Standart sapma büyüdükçe 0dan uzaklaşma artıyor

array([[  39.87212119,  129.66863713,  155.13107909,  161.93600067,
          92.34314725],
       [ -39.27250812, -239.38001349,   54.8981921 ,   96.09467992,
         -60.79324065],
       [ -72.56283139,   28.68607361, -126.76660829,   78.86218822,
         -72.97694128],
       [  56.03834797,   -1.38032028,  -32.45731474,  -41.84325203,
          21.29395669]])

In [67]:
np.random.normal(10,1,(3,4))

array([[10.6398368 ,  9.46901242, 10.48188528, 10.86291246],
       [10.76247064,  8.3914226 , 10.88736184,  9.64810857],
       [12.17391225, 10.87040451,  9.22923423,  9.71558784]])

# Random Integer'lar ile Array Oluşturmak

In [14]:
np.random.randint(1,10,(3,4)) # 1 le 10 arası 10 dahil olmayan 3e 4lük liste

array([[1, 4, 2, 7],
       [6, 8, 3, 1],
       [1, 6, 7, 3]])

In [87]:
np.random.randint(1,10,(3,5,5))

array([[[6, 7, 6, 3, 4],
        [7, 6, 2, 9, 6],
        [8, 2, 1, 7, 2],
        [1, 4, 2, 2, 6],
        [9, 7, 7, 9, 4]],

       [[9, 4, 4, 9, 7],
        [8, 5, 2, 6, 2],
        [9, 3, 9, 5, 4],
        [5, 3, 4, 1, 2],
        [5, 9, 8, 4, 1]],

       [[6, 6, 8, 8, 4],
        [9, 7, 9, 9, 9],
        [1, 3, 8, 7, 2],
        [7, 5, 2, 6, 8],
        [4, 6, 9, 7, 2]]])

In [95]:
np.random.randint(1,2)

1

In [103]:
d = {}

for _ in range(20000):
    val = np.random.randint(1,11)
    
    if val not in d:
        d[val] = 1
    else:
        d[val] += 1

In [104]:
d # her sayının ne kadar görüldüğünü gösteren bir kod

{8: 1926,
 1: 1919,
 9: 2026,
 7: 1995,
 3: 2024,
 10: 1943,
 5: 2078,
 2: 2009,
 4: 2077,
 6: 2003}

# Identity (birim) matris oluşturma

In [15]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [17]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

# Array İşlemleri

In [20]:
a = [1,2,3]
b = [2,4,8]
# iki listin çarpımı tanımlı değil
a * b

TypeError: can't multiply sequence by non-int of type 'list'

In [22]:
[2,4,8] * 3 # Aynı listi 3 defa birleştirdi

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [24]:
[2,4,8] + [2,4,8] + [2,4,8] # * 3 ile aynı işlevi gördü

[2, 4, 8, 2, 4, 8, 2, 4, 8]

In [31]:
# numpyda arrayler arası matematiksel işlemler için arraylerin eşit uzunlukta olması gerekir
x2 = np.array([1,2,3])
y2 = np.array([2,4,8,10])

x2 * y2

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [26]:
# her elemanı kendi sırasındaki ile çarpıyor
a = np.array([1,2,3])
b = np.array([2,4,8])

a * b

array([ 2,  8, 24])

In [27]:
a + b

array([ 3,  6, 11])

In [28]:
3 * a

array([3, 6, 9])

In [29]:
a = a * 3

In [30]:
a

array([3, 6, 9])

# Array attributeları

# Shape

In [34]:
x = np.zeros((2,3))

In [36]:
y = np.zeros((2,5,4))

In [37]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
x.shape

(2, 3)

In [39]:
y.shape

(2, 5, 4)

 # ndim
 ## Dimension sayısını bulur

In [42]:
x.ndim # çünkü x 2 dimensionlı

2

In [43]:
y.ndim # y 3 dimensionlı

3

# size

In [46]:
x.size # kaç elemanlı olduğunu döndürdü

6

In [47]:
y.size

40

In [48]:
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

# Dtype

In [51]:
x = np.zeros((2,3))

In [52]:
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [53]:
x.dtype

dtype('float64')

In [56]:
x = np.zeros((2,3), "int32")

In [57]:
x.dtype

dtype('int32')

In [58]:
x

array([[0, 0, 0],
       [0, 0, 0]])

# Reshape

In [6]:
# Önemli olan nokta reshape yapacağımız yapının işlemden sonraki yapıyla aynı eleman sayısına sahip olması,
#yani size'ları aynı olacak

In [7]:
a = np.arange(1,11)

In [8]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a.ndim

1

In [10]:
a.size

10

In [11]:
a.reshape(2,5) #önemli olan bu rakamların çarpımının a'nın size'ına eşit olması

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [13]:
a.reshape(2,5).ndim

2

In [16]:
a.reshape(5,2,1).ndim

3

In [19]:
a.reshape(3,3) # 3 * 3 9 eder halbuki a'nın 10 elemanı var o yüzden hata aldım

ValueError: cannot reshape array of size 10 into shape (3,3)

# -1 İle Boyuta Karar Vermek

In [21]:
a.reshape(-1,2) # -1 ile diyoruz ki ben sana bir dimensionu 2 olarak verdim diğerini sen bul, python da 5 olarak buldu

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Yeni Boyut Eklemek
## a[newaxis, :]
### newaxis kısmı neredeyse orası 1 diğer kısım da a'nın eleman sayısı kadar kolon veya satır haline dönüşür

In [3]:
a = np.arange(1,11)

In [4]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
a.shape

(10,)

In [25]:
a.ndim

1

In [31]:
a[np.newaxis, :] #a'yı bir satır 10 kolonluk hale getirdi

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [32]:
a[np.newaxis, :].shape

(1, 10)

In [33]:
a[np.newaxis, :].ndim

2

In [5]:
a[:, np.newaxis] #a'yı 10 satır, 1 kolon haline getirdi, yanı np.newaxis neredeyse orası 1 oluyor

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [37]:
a[None, :] #np.newaxis yerine bunu yazarsan da aynı sonucu alırsın

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [40]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [41]:
a[None, :].shape

(1, 10)

In [43]:
a[:, None].shape

(10, 1)

# Concatenation

In [7]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [8]:
a

array([1, 2, 3, 4])

In [9]:
b

array([5, 6, 7, 8])

In [10]:
# a veya b güncellenmez
np.concatenate([(a,b)])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# python listlerini de numpy arrayleri ile concatenate yapabiliriz

In [12]:
l = [10,11]

In [16]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [18]:
type(np.concatenate([a,b,l]))

numpy.ndarray

In [19]:
l = [10,11,11.2]

In [20]:
np.concatenate([a,b,l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [21]:
l = [10,11,'11.2']

In [22]:
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '11.2'],
      dtype='<U21')

In [23]:
l = (10,11) #tupleları da başarıyla concatenate edebiliyor

In [24]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

# Size Mismatch

In [61]:
a

array([1, 2, 3, 4])

In [65]:
x = np.array([1,2,3,4,5,6])

In [66]:
x

array([1, 2, 3, 4, 5, 6])

In [69]:
x = x.reshape(2,3)

In [70]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
a.shape # Burası önemli a'nın dimensionu sadece 1 row column mantığı yok bunda

(4,)

In [73]:
# size mismatch
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [74]:
np.concatenate([x,x]) # varsayılan oarak axis i 0 olarak aldı

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [83]:
np.concatenate([x,x], axis = 0) #x leri alt alta ekledi yani column sayısı aynı row sayısı arttı

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.concatenate([x,x], axis = 1) #xleri yan yana birleştirdi yanı satır sayısı aynı kolon sayısı arttı

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [4]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])

In [7]:
np.concatenate([array_1, array_2, array_3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
import numpy as np

# stack

In [26]:
a = np.array([1,2,3,4])

In [27]:
b = np.array([5,6,7,8])

In [28]:
a

array([1, 2, 3, 4])

In [29]:
b

array([5, 6, 7, 8])

In [30]:
a.shape

(4,)

In [31]:
b.shape

(4,)

In [33]:
np.stack([a,b]) # Default olarak axis 0 üzerinde birleştirme yapıyor

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
np.stack([a,b]).shape

(2, 4)

In [35]:
np.stack([a,b], axis = 1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [36]:
np.stack([a,b], axis = 1).shape

(4, 2)

# Splitting

In [37]:
l = [10,20,30,40,50,60,70,80]

In [38]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [41]:
# [0,1],[2,3,4,5],[6,7]
np.split(l,(2,6)) # 2 ve 6 index değeri yani diyor ki 2inci ve 6ıncı indexlerin başına bir çentik at

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [42]:
np.split(l,(3,5))

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [43]:
# Burada dikkat edilmesi gereken listleri de döndürüyor ancak array olarak

In [44]:
np.split(l,[3,7])

[array([10, 20, 30]), array([40, 50, 60, 70]), array([80])]

# Split'in Sonucunu Birden Çok Değişkene Eşitleme

In [45]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [46]:
x,y,z = np.split(l,[2,6])

In [47]:
x

array([10, 20])

In [48]:
y

array([30, 40, 50, 60])

In [49]:
z

array([70, 80])

# Vsplit
## Vertical Split

In [223]:
a = np.arange(20).reshape(2,10)

In [224]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [225]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [226]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# hsplit
## Horizontal Split

In [227]:
a = np.arange(20).reshape(2,10)

In [228]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [229]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [230]:
x,y = np.hsplit(a,[5]) # Burada indexleme yok direk kumeleri sayıyorsun 1inci 2inci 3üncü diye

In [70]:
x

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [71]:
y

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [73]:
a = np.arange(20).reshape(5,4)

In [74]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [75]:
np.vsplit(a,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

# Sorting 

In [76]:
a = np.array([20,32,5,30,10])

In [77]:
#a'yı güncellemez
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [78]:
a

array([20, 32,  5, 30, 10])

In [79]:
#a'yı günceller
a.sort()

In [80]:
a

array([ 5, 10, 20, 30, 32])

# argsort
## Küçükten büyüğe elemanların hangi indexte olduğunu döndürür

In [81]:
a = np.array([3,1,6,5,4,2])

In [82]:
# küçükten büyüğe sıralanmış elemanların indexlerini döndürür

In [86]:
sorted_idxs = np.argsort(a)

In [87]:
sorted_idxs

array([1, 5, 0, 4, 3, 2])

In [95]:
#Burası alakasız pratik
liste = [1,2,3,4,5,6,7,8,9]

In [96]:
reversed_liste = liste[::-1]

In [97]:
reversed_liste

[9, 8, 7, 6, 5, 4, 3, 2, 1]

# Multidimensional Arraylerin Elemanlarına Ulaşmak

In [98]:
a = np.arange(1,21).reshape(4,5)

In [99]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [100]:
# Her bir dimension için onun numarasını sıfırdan başlayacak şekilde yazıyorum
a[0]

array([1, 2, 3, 4, 5])

In [101]:
a[1]

array([ 6,  7,  8,  9, 10])

In [102]:
a[0][0]

1

In [104]:
a[1][0]

6

In [105]:
a[2]

array([11, 12, 13, 14, 15])

In [106]:
a[3]

array([16, 17, 18, 19, 20])

In [107]:
a[0][0]

1

In [108]:
a[0,0]

1

In [109]:
a[1,1]

7

In [110]:
#array'in veri tipi neyse ona cast olur başka veri tipine dönüştürmez
a[1,1]=20.40

In [111]:
a[1,1]

20

In [112]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [113]:
a[1,1] = "30"

In [114]:
a[1,1]

30

In [115]:
a[1,1] = "30.5"

ValueError: invalid literal for int() with base 10: '30.5'

# Slice Indexing

In [33]:
a = np.arange(1,21).reshape(4,5)

In [117]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [118]:
a[1]

array([ 6,  7,  8,  9, 10])

In [119]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [120]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [121]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [122]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
a[::-1]

array([[16, 17, 18, 19, 20],
       [11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [29]:
a[::2]# Burada ::2 yapıldığı zaman indexi göstermiyor, bu şu anlama geliyor baştan itibaren iki iki atlayarak bana göster

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [125]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [126]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [127]:
a[1:2]

array([[ 6,  7,  8,  9, 10]])

In [128]:
a[:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [129]:
a[::2,3]

array([ 4, 14])

In [130]:
a[0,2:4] #0'ıncı satır ve 2:4(4 dahil değil) arası indexin kesişimini döndür 

array([3, 4])

In [133]:
a[:2,:3] #2'ye kadar olan satırların ve 3'e kadar olan sütunların kesişimini döndür

array([[1, 2, 3],
       [6, 7, 8]])

In [36]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [38]:
 # bütün rowları al ama sadece 3. columnla kesişenleri
a[:,3]

array([ 4,  9, 14, 19])

In [39]:
a[::2,3] # ikişer ikişer atla ama 3üncü indexteki yani 4üncü kolonla kesişenleri al

array([ 4, 14])

In [41]:
a[::-1,0]

array([16, 11,  6,  1])

In [43]:
a[:2,:3] # En baştan başla 2nci indexe kadar satırları al, en baştan başla 3üncü indexe kadar sütünları al

array([[1, 2, 3],
       [6, 7, 8]])

In [44]:
a[0,2:4]

array([3, 4])

In [45]:
a[0:2,0:3]#0'ıncı index satırından 2inci index satırına kadar ve 0'ıncı index kolonundan 3üncü index kolonuna kadar kesişimleri döndür

array([[1, 2, 3],
       [6, 7, 8]])

In [47]:
a[:,:4] #Tüm satırları aldı sütunlarda da son kolon hariç

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [16]:
#Öylesine bir egzersiz
class araba:
    def __init__(self, model, speed, gas, distance = 0):
        self.model = model
        self.speed = speed
        self.gas = gas
        self.distance = self.gas * 1.3
    def getDistance(self):
        return self.distance
    def getSpeed(self):
        return self.speed
    def getGas(self):
        return self.gas

In [17]:
a = araba("renault", 130, 40)

In [18]:
araba.getSpeed(a)

130

In [19]:
araba.getDistance(a)

52.0

In [20]:
araba.getGas(a)

40

In [22]:
a = np.arange(1,21).reshape(4,5)

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [24]:
a[0]

array([1, 2, 3, 4, 5])

In [25]:
a[1]

array([ 6,  7,  8,  9, 10])

In [26]:
a[0,0]

1

In [27]:
a.ndim 

2

In [28]:
a.shape

(4, 5)

# Fancy Indexing
### Fancy indexing ile birkaç tane belli indexteki elemanları bana döndür diyebiliriz

In [48]:
x = np.arange(1,15)

In [49]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
idxs = [4,5,7,11] #Hangi indexlerdeki elemanları döndürmek istersem onların indexini herhangi bir liste kaydediyorum
#Fancy indexingde listte hangi sırayla verirsen o sırayla çağırıyor

In [57]:
x[idxs]

array([ 5,  6,  8, 12])

In [58]:
a = np.arange(12).reshape(3,4)

In [59]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a[0:2,1]

array([1, 5])

In [62]:
a[0:2,1].shape #tek boyutlu

(2,)

In [63]:
a[0:2,1].ndim

1

In [64]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [65]:
a[0:2,1:3].shape

(2, 2)

In [66]:
a[0:2,1:3].ndim

2

In [67]:
a[0,[1,3]] #0inci row ve fancy indexing ile 1 ve 3üncü indexteki column elemanlarını al diyorum

array([1, 3])

In [68]:
a[0,[1,3]].shape

(2,)

In [69]:
a[0:,[1,3]] #0dan itibaren tüm satırları al kolonlardan da sadece 1 ve 3üncü indexi al

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [70]:
a[0:,[1,3]].shape

(3, 2)

In [71]:
a.shape

(3, 4)

In [72]:
a = np.arange(20).reshape(4,5)

In [73]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [74]:
idx1 = [1,3,2]

In [75]:
idx2 = [3,0,2]

In [77]:
a[idx1,idx2] #Burada hepsini tek tek birbiri ile eşleştiriyor yani 1.idx  row ile 3.idx columnı, 3.idx row ile 0.idx column ve 2.idx row ile 2. idx column kesiştirildi 

array([ 8, 15, 12])

In [78]:
a[idx1,idx2].shape

(3,)

In [79]:
a[idx1,idx2].ndim

1

In [83]:
a[idx1][idx2] # Bunu yapmaya çalıştığım zaman idx2 yi idx1 üzerinde indexing yapmaya çalışıyorum, out of range hatası aldım 

IndexError: index 3 is out of bounds for axis 0 with size 3

In [84]:
a[idx1]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

In [85]:
a[idx2]

array([[15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [86]:
# Fancy indexing ile belli değerleri beli sonuçlara eşitlemek

In [87]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [89]:
x[[1,2,3]] = 20

In [95]:
x[1,2,3] #İkinci parantez içine koymadığım zaman xi 3 boyutlu imiş gibi alıp indexing yapmaya çalışıyor

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [96]:
x.shape

(14,)

In [97]:
x.reshape(7,2)

array([[ 1, 20],
       [20, 20],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [99]:
x = np.arange(9)

In [100]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
a  =np.arange(1,13).reshape(3,4)

In [102]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Subarray

In [106]:
a = np.arange(1,21).reshape(4,5)

In [107]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [108]:
b = a[:2,:3]

In [109]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [110]:
b.ndim

2

In [111]:
b.shape

(2, 3)

In [114]:
b[0,0] = 100 # b yi değiştirince a da değişti

In [115]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

In [121]:
b = a[:3,:3].copy() #bunu kullanınca bağımsız bir array yapmış oldum

In [122]:
b

array([[100,   2,   3],
       [  6,   7,   8],
       [ 11,  12,  13]])

In [123]:
b[0,0] = 1

In [124]:
b

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [125]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

# Conditional Indexing

In [126]:
import numpy as np

In [127]:
a = np.arange(1,10)

In [128]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [130]:
a[a<5]

array([1, 2, 3, 4])

In [131]:
filt = a < 3

In [132]:
filt

array([ True,  True, False, False, False, False, False, False, False])

In [133]:
a[filt]

array([1, 2])

In [138]:
b = np.array([2,3,3,4,5,61,7,8,11])

In [139]:
b

array([ 2,  3,  3,  4,  5, 61,  7,  8, 11])

In [140]:
a == b

array([False, False,  True,  True,  True, False,  True,  True, False])

In [141]:
a[a==b]

array([3, 4, 5, 7, 8])

In [142]:
b[b == a]

array([3, 4, 5, 7, 8])

In [143]:
#broadcasting
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [144]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [145]:
# normalde and ve or ile kurduğumuz mantığı numoyda kullanamıyoruz
(a < 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [161]:
a[(a<3) | (a>5) ] # or operator ama and gibi çalışıyor ben veya diyorum ama o hepsini alıyor

array([1, 2, 6, 7, 8, 9])

In [162]:
filt = (a < 3) | (a > 5)

In [163]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [164]:
a[(a > 3) & (a <= 5)] #and operator

array([4, 5])

# Filtrenin Değili

In [165]:
a = np.arange(1,21).reshape(4,5)

In [166]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [167]:
filt = a < 5

In [168]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [169]:
a[filt]

array([1, 2, 3, 4])

In [177]:
~((a>14) & (a<9)) # Tilda işareti ile değili yapılır ALTGR + Ü

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [180]:
filterr = ~((a<9) & (a>14))

In [181]:
a[filterr]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# Multidimensional Arraylerde Conditional Indexing

In [182]:
a = np.arange(1,21).reshape(4,5)

In [183]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [184]:
type(a)

numpy.ndarray

In [185]:
a.ndim

2

In [186]:
a.shape

(4, 5)

In [187]:
type(a<7)

numpy.ndarray

In [188]:
(a<7).shape

(4, 5)

In [189]:
(a<7).ndim

2

In [190]:
a[(a<7)]

array([1, 2, 3, 4, 5, 6])

In [191]:
a[(a<7)].shape

(6,)

In [192]:
a[(a<7)].ndim

1

In [193]:
a = np.array([1,2,3,None])

In [194]:
a

array([1, 2, 3, None], dtype=object)

In [195]:
a == None

array([False, False, False,  True])

In [196]:
a[a==None]

array([None], dtype=object)

In [197]:
*x,y,z=(4,8,15,16,23,42)

In [198]:
x

[4, 8, 15, 16]

In [200]:
l = []
for i in range(2,5,3):
    l.append(i)

In [201]:
l

[2]

In [202]:
False or True

True

In [203]:
"merhaba"[10]

IndexError: string index out of range

In [204]:
a = 7.9 + 3

In [206]:
a

10.9

In [208]:
mailler={"kisi1":"ad1.soyad1@gmail.com","kisi2":"ad2.soyad2@gmail.com","kisi3":"ad3.soyad3@gmail.com"}

In [209]:
l = []

In [210]:
for v in mailler.values():
    l.append(v)

In [211]:
l

['ad1.soyad1@gmail.com', 'ad2.soyad2@gmail.com', 'ad3.soyad3@gmail.com']

In [215]:
",".join(l)

'ad1.soyad1@gmail.com,ad2.soyad2@gmail.com,ad3.soyad3@gmail.com'

In [217]:
2==2 & print("merhaba")

merhaba


TypeError: unsupported operand type(s) for &: 'int' and 'NoneType'

In [218]:
"merhaba"[1:10]

'erhaba'

# Sum

In [3]:
a = np.arange(1,21).reshape(4,5)

In [4]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [5]:
np.sum(a)

210

In [6]:
filt = a < 5

In [7]:
np.sum(a[filt])# a arrayinin içinde 5ten küçük elemanları topladı

10

In [8]:
a[filt]

array([1, 2, 3, 4])

In [9]:
fit = (a>5) & (a<9)

In [10]:
a[fit]

array([6, 7, 8])

In [11]:
np.sum(a[fit])

21

In [27]:
reverse_filter = ~((a>5) & (a<9))

In [28]:
a[reverse_filter]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [30]:
np.sum(a[reverse_filter])

189

# Belirli bir aksis üzerinde toplama

In [31]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
np.sum(a,axis=0) # alt alta topluyor

array([34, 38, 42, 46, 50])

In [38]:
# Önemli not : Toplamayı hangi axis üzerinden yapıyorsanız o aksisin yok olması gerekiyor
# örneğin bu (4,5) lik arrayda axis 0 üzerinden toplam yaptıpın zaman 4 yok olur sadece 5 kalır

In [40]:
np.sum(a,axis = 1) #yan yana topluyor

array([15, 40, 65, 90])

# All
## Tüm elemanlar verilen şartı sağlıyor mu diye kontrol etmek için kullanılır

In [41]:
a = np.arange(20).reshape(4,5)

In [42]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [43]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [44]:
a[a>-1]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
np.all(a>-1)

True

In [46]:
np.all(a>5)

False

In [47]:
filt = a>-1

In [48]:
a[filt]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
filt

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [53]:
np.all(a>2, axis = 0)

array([False, False, False,  True,  True])

# Any
## All'a çok benziyor tek farkı herhangi bir eleman verilen şartı sağlıyorsa True döndürüyor

In [56]:
import numpy as np

In [57]:
a = np.arange(20).reshape(4,5)

In [58]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [60]:
np.any(a>17)

True

In [63]:
np.any(a>17, axis=0)

array([False, False, False,  True,  True])

In [64]:
np.any(a>17, axis=1)

array([False, False, False,  True])

In [65]:
b = np.arange(1,21).reshape(4,5)

In [66]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [67]:
np.any(b>4, axis=0)

array([ True,  True,  True,  True,  True])